### ISSUE TITLE
Color Layer Prediction

### ISSUE THREAD

**Issue by BaileyRobbins** [google/stereo-magnification#10]
Hi, 
I was curious to see the results with the other options of 'which_color_pred' in mpi_from_images.py script, but values other than 'bg' give me error:
"tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [128] rhs shape= [67]"

Wondering if anyone is able to get other prediction methods to work?

Thanks!

**Comment by snaves** [comment]
Hi,

The model that we released is specifically trained for the 'bg' setting. In general, for our paper, a model is trained for a specific setting of this 'which_color_pred' option, and can't be used for other settings. If there is a reason you would like to see the performance of other models, we can look into releasing additional models. (We released the 'bg' model because that performed the best in our tests.) Or, you can try to train a model yourself with a different setting.

**Comment by BaileyRobbins** [comment]
I see, ok thanks!
